# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87ff6ee834e23ddcfec13d1de11c8af808e6d94bfbb474f5c8d8632a8fe1bd89c20488ad0d796fc0647188e56b7c8c09d4ec81f95ac9bf86039fa19b9b518797

test:
  secret_key_base: f4349b3cc08e5c5f4cf9853abfe061e4c6cb2616472010555ff96f08ff07e36f56e263023f61730cb09a4f065ee87ac850a56baaac8219f7f4650e3fc322fb86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
